import os
import logging
import yfinance as yf
from datetime import datetime
import pytz
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes
from apscheduler.schedulers.asyncio import AsyncIOScheduler

# --- ១. ការកំណត់ CONFIG (ទាញចេញពី Railway Variables) ---
# ប្រើ .get(..., '') ដើម្បីកុំឱ្យវា Crash ពេលកំពុង Build
TOKEN = os.environ.get('BOT_TOKEN', '')
CHAT_ID = os.environ.get('MY_CHAT_ID', '')

# កំណត់ Logging ដើម្បីមើល Error ក្នុង Railway Logs
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)

# --- ២. មុខងារវិភាគទិន្នន័យមាស (Intelligence Logic) ---
def get_intelligence_report():
    try:
        # ទាញយកទិន្នន័យ Gold (GC=F) និង DXY
        gold = yf.download('GC=F', period='5d', interval='1h', progress=False)
        dxy = yf.download('DX-Y.NYB', period='5d', interval='1h', progress=False)
        
        curr_p = float(gold['Close'].iloc[-1])
        pdh = float(gold['High'].iloc[-2])
        pdl = float(gold['Low'].iloc[-2])
        dxy_val = float(dxy['Close'].iloc[-1])
        
        # កំណត់ Bias តាមបច្ចេកទេស Sniper
        bias = "BULLISH 🚀" if curr_p > pdh else "BEARISH 📉" if curr_p < pdl else "NEUTRAL ↔️"
        
        report = (
            f"🏛 *E11 GLOBAL INTELLIGENCE V40*\n"
            f"⏰ `{datetime.now(pytz.timezone('Asia/Phnom_Penh')).strftime('%H:%M')} (Cambodia)`\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"💰 *XAUUSD PRICE:* `${curr_p:.2f}`\n"
            f"📊 *BIAS:* {bias}\n\n"
            f"🌍 *MARKET CONTEXT:*\n"
            f"• DXY Index: `{dxy_val:.2f}`\n"
            f"• PDH (Resistance): `${pdh:.2f}`\n"
            f"• PDL (Support): `${pdl:.2f}`\n\n"
            f"📅 *INSIGHT:* ទីផ្សារមាសខែមេសា ២០២៦ កំពុងតាមដានកត្តាភូមិសាស្ត្រនយោបាយ។\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"✅ _Generated by E11 Master Sniper System_"
        )
        return report
    except Exception as e:
        logging.error(f"Error fetching data: {e}")
        return "⚠️ Error: មិនអាចទាញយកទិន្នន័យបានទេ ក្នុងពេលនេះ!"

# --- ៣. មុខងាររបស់ Telegram Bot ---
async def send_auto_report(application):
    if CHAT_ID:
        report = get_intelligence_report()
        await application.bot.send_message(
            chat_id=CHAT_ID, 
            text=report, 
            parse_mode='Markdown',
            message_thread_id=2  # បាញ់ចូល Topic Report
        )

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("🎯 E11 Intelligence Bot Active! ប្រើ /report ដើម្បីមើលទិន្នន័យ។")

async def manual_report(update: Update, context: ContextTypes.DEFAULT_TYPE):
    report = get_intelligence_report()
    await update.message.reply_text(report, parse_mode='Markdown')

# --- ៤. ចំណុចចាប់ផ្ដើមរត់ (Main Entry) ---
if __name__ == '__main__':
    if not TOKEN:
        print("❌ Error: រកមិនឃើញ BOT_TOKEN ក្នុង Variables ទេ!")
    else:
        application = ApplicationBuilder().token(TOKEN).build()
        
        # បន្ថែម Command
        application.add_handler(CommandHandler('start', start))
        application.add_handler(CommandHandler('report', manual_report))
        
        # កំណត់ម៉ោងរោទ៍ (ច័ន្ទ-សុក្រ ម៉ោង ៨:០០ ព្រឹក)
        scheduler = AsyncIOScheduler(timezone="Asia/Phnom_Penh")
        scheduler.add_job(send_auto_report, 'cron', day_of_week='mon-fri', hour=8, minute=0, args=[application])
        scheduler.start()
        
        print("🚀 Bot កំពុងដំណើរការ...")
        application.run_polling()
        
