import os
import logging
import yfinance as yf
from datetime import datetime
import pytz
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes
from apscheduler.schedulers.asyncio import AsyncIOScheduler

# --- ១. ការកំណត់ CONFIG ---
TOKEN = os.environ.get('BOT_TOKEN', '')
CHAT_ID = os.environ.get('MY_CHAT_ID', '')

# កំណត់ Logging ដើម្បីឆែកមើលជំងឺក្នុង Railway Logs
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO
)
logger = logging.getLogger(__name__)

# --- ២. មុខងារវិភាគទិន្នន័យមាស ---
def get_intelligence_report():
    try:
        # ទាញយកទិន្នន័យ Gold និង DXY
        gold = yf.download('GC=F', period='5d', interval='1h', progress=False)
        dxy = yf.download('DX-Y.NYB', period='5d', interval='1h', progress=False)
        
        curr_p = float(gold['Close'].iloc[-1])
        pdh = float(gold['High'].iloc[-2])
        pdl = float(gold['Low'].iloc[-2])
        dxy_val = float(dxy['Close'].iloc[-1])
        
        bias = "BULLISH 🚀" if curr_p > pdh else "BEARISH 📉" if curr_p < pdl else "NEUTRAL ↔️"
        
        report = (
            f"🏛 *E11 GLOBAL INTELLIGENCE V40*\n"
            f"⏰ `{datetime.now(pytz.timezone('Asia/Phnom_Penh')).strftime('%H:%M')} (Cambodia)`\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"💰 *XAUUSD PRICE:* `${curr_p:.2f}`\n"
            f"📊 *BIAS:* {bias}\n\n"
            f"🌍 *MARKET CONTEXT:*\n"
            f"• DXY Index: `{dxy_val:.2f}`\n"
            f"• PDH (Resistance): `${pdh:.2f}`\n"
            f"• PDL (Support): `${pdl:.2f}`\n\n"
            f"📅 *INSIGHT:* ទីផ្សារមាសខែមេសា ២០២៦ កំពុងតាមដានកត្តា DXY និងការប្រែប្រួលភូមិសាស្ត្រនយោបាយ។\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"✅ _Generated by E11 Master Sniper System_"
        )
        return report
    except Exception as e:
        logger.error(f"Error fetching data: {e}")
        return "⚠️ Error: មិនអាចទាញយកទិន្នន័យបានទេ ក្នុងពេលនេះ!"

# --- ៣. មុខងារបាញ់សារ ---

# មុខងារបាញ់អូតូតាមម៉ោង (បាញ់ចូល Group ID ដែលកំណត់)
async def send_auto_report(application):
    if CHAT_ID:
        try:
            report = get_intelligence_report()
            # បើជា Group ដែលមាន Topic អាចថែម message_thread_id បាន
            await application.bot.send_message(
                chat_id=CHAT_ID, 
                text=report, 
                parse_mode='Markdown'
            )
            logger.info(f"Auto-report sent to {CHAT_ID}")
        except Exception as e:
            logger.error(f"Failed to send auto-report: {e}")

# Command /start
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_id = update.effective_chat.id
    logger.info(f"User {user_id} started the bot")
    await update.message.reply_text("🎯 E11 Intelligence Bot Active! ប្រើ /report ដើម្បីមើលទិន្នន័យ។")

# Command /report (ឆ្លើយតបគ្រប់កន្លែង)
async def manual_report(update: Update, context: ContextTypes.DEFAULT_TYPE):
    report = get_intelligence_report()
    # ឆែកមើលថា តើសារមកពី Topic ឬ Chat ផ្ទាល់ខ្លួន
    thread_id = update.effective_message.message_thread_id if update.effective_message.is_topic_message else None
    
    try:
        await update.message.reply_text(
            report, 
            parse_mode='Markdown', 
            message_thread_id=thread_id
        )
        logger.info(f"Manual report sent to {update.effective_chat.id}")
    except Exception as e:
        logger.error(f"Manual report failed: {e}")

# --- ៤. ចំណុចចាប់ផ្ដើម ---
if __name__ == '__main__':
    if not TOKEN:
        logger.error("❌ Error: BOT_TOKEN មិនត្រូវបានកំណត់!")
    else:
        # បង្កើត Application
        application = ApplicationBuilder().token(TOKEN).build()
        
        # បន្ថែម Command
        application.add_handler(CommandHandler('start', start))
        application.add_handler(CommandHandler('report', manual_report))
        
        # កំណត់ម៉ោងរោទ៍ (ច័ន្ទ-សុក្រ ម៉ោង ៨:០០ ព្រឹក កម្ពុជា)
        scheduler = AsyncIOScheduler(timezone="Asia/Phnom_Penh")
        scheduler.add_job(send_auto_report, 'cron', day_of_week='mon-fri', hour=8, minute=0, args=[application])
        scheduler.start()
        
        logger.info("🚀 Bot កំពុងដំណើរការ... កំពុងរង់ចាំ Command ពីមេ!")
        application.run_polling()
        
